apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: invoice
  name: invoice
  labels:
    app: invoice
spec:
  selector:
    matchLabels:
      app: invoice
  template:
    metadata:
      labels:
        app: invoice
        name: invoice
    spec:
      containers:
        - name: invoice
          image: shreya-intelops/procurement-solution/invoice
          imagePullPolicy: Always
        
          env:
            - name: SERVICE_NAME
              value: "go-app"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "localhost:4317"
            - name: INSECURE_MODE
              value: "true"
        
          ports:
        
        
          - containerPort: 4500
            name: http
        
        
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
        